[package]
name = "advent2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parse-display = "0.5.3"
itertools = "0.10.3"
hex = "0.4.3"
bitvec = "0.22.3"